### ISSUE TITLE
Are latest added requirements really requirements?

### ISSUE THREAD

**Issue by buhrmann** [conda-forge/nltk-feedstock#7]
Hi, investigating a ballooning conda environment I noticed that when I pip install nltk I get "six" as the only installed dependency. When I conda install, in contrast, I get hundreds of MB of other packages, including e.g. qt (via matplotlib I assume). Have the following really become hard requirements suddenly? 

- gensim
- numpy
- python-crfsuite
- scikit-learn
- scipy
- matplotlib
- pyparsing
- twython
- requests

That would make it sort of prohibitive to use in a production environment.

**Comment by quartox** [comment]
I believe this relates to the https://github.com/conda/conda/issues/7502 discussion of optional dependencies similar to `extras_require` in the `setup.py`. Seems like a metapackage may solve the problem (not entirely sure) but since this recipe doesn't have a large group of maintainers might be too much work.

**Comment by quartox** [comment]
Fixed by #8, could make a metapackage called `nltk-all` with full dependencies to get all requirements in there.
